### ISSUE TITLE
After disabling BTTV Tab autocomplete not working for majority emotes

### ISSUE THREAD

**Issue by vibrasphere** [Lordmau5/BTTV4FFZ#12]
No more FeelsGoodMan, FeelsBadMan, all Feels* emotes or RonSmug.

They render in chat, but no more autocomplete for them and have to type manually entire thing.

**Comment by Lordmau5** [comment]
Are you using FFZ, BTTV and BTTV4FFZ in combination?

Get rid of BTTV if that's the case :P

**Comment by SirStendec** [comment]
(Sounds more to me like they removed BTTV, and that the issue was they didn't have FFZ set to tab-complete global emotes. That is now the default setting as of today, so hopefully it's not-a-bug.)
