### ISSUE TITLE
[Request] Userscript version

### ISSUE THREAD

**Issue by RedSnt** [Lordmau5/BTTV4FFZ#14]
So someone asked in chat on twitch how to get BTTV emotes for Edge and luckily there is a userscript version and Tampermonkey support for edge for both BTTV and FFZ, but not this awesome and honestly required (when using FFZ) addon/extension. 

Then again, I don't know how BTTV4FFZ interacts with FFZ, probably by injecting code so that might be hard using a userscript version.

**Comment by Lordmau5** [comment]
You could add this script in Tampermonkey and see if it works:
https://cdn.lordmau5.com/inject.js

It's basically the injection script that is also being loaded by the Chrome and Firefox extension.
Always up-to-date :)

I should probably mention that in the Readme + on the website

**Comment by RedSnt** [comment]
Works perfectly mate!

Just needed to add: 

```
// @include		http://twitch.tv/*
// @include		https://twitch.tv/*
// @include		http://*.twitch.tv/*
// @include		https://*.twitch.tv/*
//
// @exclude		http://api.twitch.tv/*
// @exclude		https://api.twitch.tv/*
```

to make it activate on Twitch.

Ez life :D

**Comment by Lordmau5** [comment]
Neat! :)

So what did you do now?
Grab the content of the inject.js file and include the content in your comment at the top of it?

**Comment by RedSnt** [comment]
I just made a new script in tampermonkey, copy pasted from your inject.js file, opened the FFZ userscript in the editor then copy pasted that @include and @exclude code in the header to make it work.

**Comment by Lordmau5** [comment]
If I do updates, you're not gonna be able to get them then, bit annoying...

Can you inject scripts through Tampermonkey as well?

If so, have a look at this and check if it's possible to implement it this way:
https://github.com/Lordmau5/BTTV4FFZ/blob/master/Chrome/chrome/script.js

**Comment by RedSnt** [comment]
I'm not good at coding unfortunately, but you should have a look at how FFZ does its userscript 'cause that is basically just injecting the code from another place, not the tampermonkey script itself:

[https://cdn.frankerfacez.com/script/ffz_injector.user.js](https://cdn.frankerfacez.com/script/ffz_injector.user.js)

**Comment by Lordmau5** [comment]
Yup, from what I see you just need to put the contents of the file I linked in the Tampermonkey script :)

**Comment by RedSnt** [comment]
Did a hack job, but this userscript works just fine:

```
// ==UserScript==
// @id			BTTV4FFZ
// @name		BetterTTV Emotes for FrankerFaceZ
// @namespace	BTTV4FFZ
//
// @version		1.3.8
// @updateURL	https://cdn.lordmau5.com/inject.js
//
// @description	Ever wanted to have these slick Better Twitch TV emotes but you already have FrankerFaceZ installed? BetterTwitchTV for FrankerFaceZ takes care of that problem.
// @homepage	https://lordmau5.com/bttv4ffz/
// @icon		Kappa
// @icon64		Kappa
// @icon128		Kappa
//
// @include		http://twitch.tv/*
// @include		https://twitch.tv/*
// @include		http://*.twitch.tv/*
// @include		https://*.twitch.tv/*
//
// @exclude		http://api.twitch.tv/*
// @exclude		https://api.twitch.tv/*
//
// @grant		none
// @run-at		document-end
// ==/UserScript==

function inject() {
    var s = document.createElement('script');
    s.src = "https://cdn.lordmau5.com/inject.js";
    s.onload = function() {
        this.parentNode.removeChild(this);
    };
    (document.head || document.documentElement).appendChild(s);
}

inject();
```

Might want to either get rid of those @icon's if you don't have them laying around - they're only really used in Tampermonkey anyway.

**Comment by Lordmau5** [comment]
A userscript version is now available to download from the website :)
Thanks for the rough draft of the script :P
