### ISSUE TITLE
bttv global emotes

### ISSUE THREAD

**Issue by residentflexoffender** [Lordmau5/BTTV4FFZ#16]
SourPLS shows up twice in the tab menu when I type in Sour

Is there a way to add them into the emote picker?

I'm using windows10, opera 42.0 stable, with violent monkey to inject the bttv4ffz v1.1.4 script

**Comment by Lordmau5** [comment]
SourPLS currently shows up twice, because BTTV's API endpoint has them listed twice. I'm not checking for that.

It'll be gone once they remove the holiday emotes. Also, it's prioritizing the holiday emotes anyway, so it's just a visual bug that the non-holiday emote shows up :)

As for the emote picker - what do you mean by that??

**Comment by residentflexoffender** [comment]
![emotes](https://cloud.githubusercontent.com/assets/24578105/21232878/367bed72-c2bb-11e6-9e5e-3337093d4cac.png)

I mean down here, I understand that the screen shot is only showing the channel emotes.

![emotes2](https://cloud.githubusercontent.com/assets/24578105/21232971/819e7eaa-c2bb-11e6-8e0a-bd149f4f9249.png)

Then there's this section, where I figure it should display the global bttv emotes. where exactly it should go, I don't know. However I was looking for them under [All Emotes] initially. Maybe an additional section be added beside [Emoji] for [BTTV].

Essentially the "Show emotes in Emotion Menu" option implied to me that the global emotes would be available somewhere, and not just the channel emotes.

**Comment by Lordmau5** [comment]
You also need to enable this in FFZ :)
![image](https://cloud.githubusercontent.com/assets/1345036/21233165/79793f2a-c2ee-11e6-8aad-b6247c9d9364.png)

**Comment by residentflexoffender** [comment]
Well I'll be. Thanks!
