### ISSUE TITLE
chrome extension asking for weird permission?

### ISSUE THREAD

**Issue by CArchetype** [Lordmau5/BTTV4FFZ#18]
Why is the chrome extension now asking for permission to "read and change info on multiple websites" (or something like that)

I use FF myself but many of my friends are using the addon and they're concerned what this means (since it's not obvious)

**Comment by CArchetype** [comment]
Also, unrelated, will FFZ Addon Pack have Firefox support? It would be a shame to have to go back to BTTV

**Comment by Lordmau5** [comment]
![image](https://cloud.githubusercontent.com/assets/1345036/22257845/88e6d7f2-e25f-11e6-9e03-5ea177bfe3e5.png)
![image](https://cloud.githubusercontent.com/assets/1345036/22257847/8f16a5c6-e25f-11e6-8ac8-b9ca6da8ed8b.png)

Though accessing frankerfacez.com will not be needed anymore, I don't even know why I had that before lol...
So yea, I need access to:
- betterttv, to do API requests to their server
- lordmau5.com, to request the actual FFZ:AP script
- twitch.tv, to inject said script into the website

As for Firefox, I actually wanted to ditch it, but I mean, I can add it again.
Users will have to install it via. the website again though, I will not be able to have it on their addons page anymore.

**Comment by CArchetype** [comment]
Thanks for the reply, that makes sense.

Also it would be great if you could keep support for Firefox. FFZ is already not on their addons page so it's not a problem if FFZ Add-On Pack isn't there either.

**Comment by Lordmau5** [comment]
Alright, I'll make sure to re-add Firefox support later once I'm done writing up a better README for the new repository :)

**Comment by Lordmau5** [comment]
Alright, a Firefox build is back up.

Check the "Download" section on the new repository :)

https://github.com/Lordmau5/The-FFZ-Addon-Pack
