### ISSUE TITLE
Gamewisp sub button issue

### ISSUE THREAD

**Issue by AneiDoru** [Lordmau5/BTTV4FFZ#19]
it goes to https://gamewisp.comusername/
instead of https://gamewisp.com/username/
please fix

**Comment by Lordmau5** [comment]
Wait what how when why... what? 

Did I accidentally ship in-dev stuff to the public?! 

Either way, 2 things:
- Wrong repository, please post this issue on https://github.com/Lordmau5/The-FFZ-Addom-Pack
- Gamewisp stuff is not supposed to be released to the public yet, which means it's unfinished :) 

~ Greetings!
