### ISSUE TITLE
Unable to send any emotes in chat

### ISSUE THREAD

**Issue by eternalnami** [Lordmau5/BTTV4FFZ#2]
I can type the emote into the chat box but enter stops working.  
https://www.youtube.com/watch?v=3AvKWJFcW-4&feature=youtu.be
I've done all normal troubleshooting, restarting chrome, removing the plugin and restarting chrome and re-adding it.  I've also cleared my FFZ settings to default.  I have the same settings over 3 PC and it is only affecting one of them. I have also disabled every other extension but FFZ and BTTV emotes, the problem only arises when BTTV emotes is active, if I disable it I can enter, but can't see them. 
Also Github won't let me add my settings even after zipping it.

**Comment by Lordmau5** [comment]
What other addons do you have installed?
I really can't reproduce this...

In the emote menu, do you see a "tab" for the BTTV emotes?
If you do, can you click the emotes in that and try sending it that way?
Also, what happens if you manually click "Send" instead of pressing enter?

**Comment by eternalnami** [comment]
I have tested it with no other addons installed, only FFZ and BTTV emotes.

I do have the tab for the BTTV emotes, manually clicking them does the same thing, puts the text into the box but won't send.  Also manually clicking send doesn't allow it though either.

All 3 PC's are on chrome Version 49.0.2623.87 m, Windows 10 64bit, I could get a list of exact patches if needed but it'd be big.

Other addons if really needed are: 
BTTV emotes for FFZ
Disconnect (disabled on *.twitch.*)
FFZ
HTTPS Everywhere
Magic Actions for youtube
MaiWaifu
Privacy Badger (disabled on *.twitch.*)
PSO2 Extention
RES
Steam Inventory helper
uBlock Origin (disabled on *.twitch.*)

**Comment by eternalnami** [comment]
I just woke up and instantly checked this post, so extremely sorry but I opened twitch and I am able to send the emotes now.  Nothing has changed, I didn't reboot my PC overnight (downloading stuff) nor shut down chrome.  I checked the same emotes in the same channel, works.  God I hate comptuers....  Thank you Lordmou5 for all the work you do.

**Comment by Lordmau5** [comment]
Alright, sweet. So it was a FFZ or Twitch problem ;)
Let's just say that this also happened before Stendec pushed out a fix:
![Image](https://i.lordmau5.com/1458670059-795.png)

**Comment by eternalnami** [comment]
I would guess it was a FFZ problem, but it's just random it wouldn't let me even post it into chat, other people could type it.  But it works now, again thanks for the work!
