### ISSUE TITLE
BTTV PRO STILL BROKEN

### ISSUE THREAD

**Issue by LawlyPopz** [Lordmau5/BTTV4FFZ#9]
This has been broken for the past 60 days when will it get fixed???

![a52d7](https://cloud.githubusercontent.com/assets/9284733/17462864/9d8e49e4-5cb1-11e6-8dd1-775546c6bc19.png)
 this is still broken 
![af1a4](https://cloud.githubusercontent.com/assets/9284733/17462868/c4a556c6-5cb1-11e6-819b-26c55f714a75.png) 

when it should look like this 
![2ea2e](https://cloud.githubusercontent.com/assets/9284733/17462873/cbd43084-5cb1-11e6-99e8-ca1907373cd7.png)

Please fix this!!!!

**Comment by Lordmau5** [comment]
I don't have a BTTV Pro subscription to test it out and will not get one just for this.
Seeing that you have one (and that you ripped of my code successfully already into your own repo, though the DMCA seems to be a nice effect, right?), why not do a pull request and get it fixed?

Also, no one has reported issues with it yet, so it's pretty much just you that has these issues.
